name: Selenium Opencart Workflow
on: 
  workflow_dispatch:
    
          
permissions:
  id-token: write
  contents: read
  
jobs:
  starting_regression_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Selenium + TestNG Tests
        run: mvn clean test -DsuiteXmlFile=testng_regression.xml

        
      # - name: Archive test reports (optional)
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: testng-reports
      #     path: test-output/
